### ISSUE TITLE
Error integrating codimension 1 function against codimension 0 function along facets

### ISSUE THREAD

**Issue by drtloudon** [jpdean/mixed_domain_demos#26]
In your "hdg_poisson.py" example I get the error, "RuntimeError: Point dim (2) does not match element dim (1)." when trying to assemble the a_10 form. I recently updated to dolfinx version 0.8.0, which perhaps is the issue. I'm trying to assemble a similar bilinear form for a related problem. Any ideas how to fix this?

**Comment by jpdean** [comment]
Thanks for this. The reason you're getting that error is because DOLFINx 0.8.0 doesn't support mixed-domain integrals of codimension 1. Support is added in [this](https://github.com/FEniCS/dolfinx/pull/3224) PR. When it gets merged, I'll update the demos in this repo.

If you want to try it now, you would need to install [this](https://github.com/FEniCS/ffcx/pull/675) FFCx branch and the above DOLFINx branch. Otherwise, just wait till they land in main :)
